-- CREATE TABLE users (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   first_name VARCHAR(100) NOT NULL,
--   last_name VARCHAR(100) NOT NULL,
--   gender ENUM('Male', 'Female', 'Other') NOT NULL,
--   ethnicity VARCHAR(100),
--   email VARCHAR(255) NOT NULL UNIQUE,
--   phone_number VARCHAR(20),
--   zipcode VARCHAR(20),
--   password VARCHAR(255) NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );